version: '3'
services:
 node_kontti:
  image: my-app:1.0
  ports: 
   - 3001:3001
  depends_on:
   - mongodb_kontti
 mongodb_kontti:
  image: mongo:4.4.6
  ports:
   - 27017:27017
  environment:
   - MONGO_INITDB_ROOT_USERNAME=admin 
   - MONGO_INITDB_ROOT_PASSWORD=password
  volumes:
   - mongo-data:/data/db
 mongo-express_kontti:
  image: mongo-express
  ports:
   - 8080:8081
  environment:
   - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
   - ME_CONFIG_MONGODB_ADMINPASSWORD=password
   - ME_CONFIG_MONGODB_SERVER=mongodb_kontti
  depends_on: 
   - mongodb_kontti
volumes:
  mongo-data:
    driver: local