version:'3'
services:
	mongodb_kontti:
	    image: mongo:4.4.6
	    ports:
	      - 27017:27017
	    environment:
	      - MONGO_INITDB_ROOT_USERNAME=admin 
	      - MONGO_INITDB_ROOT_PASSWORD=password
	  mongo-express_kontti:
		image: mongo-express
	    	ports:
	      	- 8080:8080
	    	environment:
          - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
          - ME_CONFIG_MONGODB_ADMINPASSWORD=password
          - ME_CONFIG_MONGODB_SERVER=mongodb_kontti 

